#!/bin/bash
#PBS -q workq
#PBS -A hpc_sel_smic_4
#PBS -l nodes=4:ppn=20
#PBS -l walltime=72:00:00
#PBS -o Marex.out
#PBD -j Marex.err
#PBS -M dholstein1@lsu.edu
#PBS -N MAR

module load netcdf-fortran/4.5.2/intel-19.0.5-mvapich-2.3.3
#module load intel
cd $PBS_O_WORKDIR
mpirun -f $PBS_NODEFILE -np 80 ./cms MARex
